language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
    - packages/web-client/node_modules
    - packages/api/node_modules
install: 
  - npm install
  - lerna bootstrap
script:
  - lerna run test
  - lerna run build